### ISSUE TITLE
Fixing the carousel slider for user reviews section

### ISSUE THREAD

**Issue by anilphiyak617** [anilphiyak617/Quicky-Owner-Frontend#3]
Creating Carousel Component as react-elastic-carousel is having dependency issues with next@13 take reference from /components/ImageSlider.js it has data and sources

**Comment by bilalshaikh292** [comment]
Heyy I would like to contribute ?

**Comment by anilphiyak617** [comment]
> Heyy I would like to contribute ?

Ok you can proceed with it
